### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by syedmaazsaeed**
BRMS (banking record management system) Python project

### CODE REVIEW

**Comment by syedmaazsaeed** [comment]
Any type of question then ask me.

**Review by ZeeshanMukhtar1 — CHANGES_REQUESTED** [review]
Hi @syedmaazsaeed ,
Thanks for your recent code contribution ('BANKING_MANAGEMENT_SYSTEM_PROJECT(DATABASE).py'). Please create a dedicated folder in the project's directory that aligns with the code's category for better organization and error-free code placement. If you need guidance, feel free to ask. 
### We value your contributions to maintaining code quality. 😊

Best regards.

**Comment by syedmaazsaeed** [comment]
Hi @ZeeshanMukhtar1 How should I contribute, and what should the code be like? I have a lot of confusions.You can help me ...

**Comment by ZeeshanMukhtar1** [comment]
> Hi @ZeeshanMukhtar1 How should I contribute, and what should the code be like? I have a lot of confusions.You can help me ...

If U have confusion with PR plz check [this guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)

**Comment by syedmaazsaeed** [comment]
It's not my efforts it's your efforts. I am Thankful to you..

**Pull request merged**
