### PR TITLE
Adding C# Basic to Advanced guide and source code (practise Programs )  ideal for beginners and intermediate users. Also included various projects for practical application.

### PR DESCRIPTION
**Pull request by syedmaazsaeed**
A structured C# guide with source code programs useful for beginners and intermediate users has been included with this commit. 

The resource folders are labeled { CSharp Basic } -  { CSharpAdvance }  and  { Code + Projects }  making resource discovery effortless.

### CODE REVIEW

**Comment by syedmaazsaeed** [comment]
Thanks @ZeeshanMukhtar bro! You are a real Gem  because you are working everywhere, whether it's LinkedIn, GitHub, 
Discord, Slack, or building websites and apps ......
 
Your mind works 24/7 ⏳ either you are sleeping or waking, & your thinking power is outclass  no words  Bro....

Your mind is always active 💭.  

Everyone wants to be like You especially me 👨‍💻. 

May ALLAH Grant you even more & more success beyond words. { Keep growing } { stay blessed } { Always Happy } .

 You are the true  developer and a role model for others.

**Comment by ZeeshanMukhtar1** [comment]
> Thanks @zeeshanmukhtar bro! You are a real Gem because you are working everywhere, whether it'-s LinkedIn, GitHub👨‍💻 , Discord, Slack, or building websites and apps ......
> 
> Your mind works 24/7 ⏳ either you are sleeping or awake & your thinking power is outclass no words Bro....
> 
> Your mind is always active 💭.
> 
> Everyone wants to be like You especially me 👨‍💻.
> 
> May ALLAH Grant you even more & more success beyond words. { Keep growing } { stay blessed } { Always Happy } .
> 
> You are the true developer and a role model for others.



Thank you so much @syedmaazsaeed  for your kind words! Wishing you all the best on your journey as well—keep shining!

**Comment by syedmaazsaeed** [comment]
Pleasure Bro. 🧑‍💻💭⏳

**Comment by AasmaRaza7** [comment]
> > Thanks @zeeshanmukhtar bro! You are a real Gem because you are working everywhere, whether it'-s LinkedIn, GitHub👨‍💻 , Discord, Slack, or building websites and apps ......
> > Your mind works 24/7 ⏳ either you are sleeping or awake & your thinking power is outclass no words Bro....
> > Your mind is always active 💭.
> > Everyone wants to be like You especially me 👨‍💻.
> > May ALLAH Grant you even more & more success beyond words. { Keep growing } { stay blessed } { Always Happy } .
> > You are the true developer and a role model for others.
> 
> Thank you so much @syedmaazsaeed for your kind words! Wishing you all the best on your journey as well—keep shining!

zeeshan i am getting notifications and emails of everything that you are doing on git hub. please remove me if i m not needed in your work

**Comment by ZeeshanMukhtar1** [comment]
"Hi @AasmaRaza7 , I've removed you from the repository as requested; thank you for your contributions
image

**Pull request merged**
